//
//Copyright 2025 The maco Authors
//
//This program is offered under a commercial and under the AGPL license.
//For AGPL licensing, see below.
//
//AGPL licensing:
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU Affero General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU Affero General Public License for more details.
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.28.3
// source: api/types/internal.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventKind int32

const (
	EventKind_EventUnknown EventKind = 0
)

// Enum value maps for EventKind.
var (
	EventKind_name = map[int32]string{
		0: "EventUnknown",
	}
	EventKind_value = map[string]int32{
		"EventUnknown": 0,
	}
)

func (x EventKind) Enum() *EventKind {
	p := new(EventKind)
	*p = x
	return p
}

func (x EventKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventKind) Descriptor() protoreflect.EnumDescriptor {
	return file_api_types_internal_proto_enumTypes[0].Descriptor()
}

func (EventKind) Type() protoreflect.EnumType {
	return &file_api_types_internal_proto_enumTypes[0]
}

func (x EventKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventKind.Descriptor instead.
func (EventKind) EnumDescriptor() ([]byte, []int) {
	return file_api_types_internal_proto_rawDescGZIP(), []int{0}
}

// Minion defines the base information of maco-minion
type Minion struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Name     string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Uid      string                 `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Ip       string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Hostname string                 `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Tags     map[string]string      `protobuf:"bytes,5,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// operation system
	Os string `protobuf:"bytes,6,opt,name=os,proto3" json:"os,omitempty"`
	// cpu architecture
	Arch string `protobuf:"bytes,7,opt,name=arch,proto3" json:"arch,omitempty"`
	// the version of minion
	Version string `protobuf:"bytes,8,opt,name=version,proto3" json:"version,omitempty"`
	// registry time
	RegistryTimestamp int64 `protobuf:"varint,21,opt,name=registry_timestamp,json=registryTimestamp,proto3" json:"registry_timestamp,omitempty"`
	// the timestamp of minion connects to server
	OnlineTimestamp int64 `protobuf:"varint,22,opt,name=online_timestamp,json=onlineTimestamp,proto3" json:"online_timestamp,omitempty"`
	// the timestamp of minion offline
	OfflineTimestamp int64 `protobuf:"varint,23,opt,name=offline_timestamp,json=offlineTimestamp,proto3" json:"offline_timestamp,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Minion) Reset() {
	*x = Minion{}
	mi := &file_api_types_internal_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Minion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Minion) ProtoMessage() {}

func (x *Minion) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_internal_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Minion.ProtoReflect.Descriptor instead.
func (*Minion) Descriptor() ([]byte, []int) {
	return file_api_types_internal_proto_rawDescGZIP(), []int{0}
}

func (x *Minion) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Minion) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *Minion) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Minion) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Minion) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Minion) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Minion) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *Minion) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *Minion) GetRegistryTimestamp() int64 {
	if x != nil {
		return x.RegistryTimestamp
	}
	return 0
}

func (x *Minion) GetOnlineTimestamp() int64 {
	if x != nil {
		return x.OnlineTimestamp
	}
	return 0
}

func (x *Minion) GetOfflineTimestamp() int64 {
	if x != nil {
		return x.OfflineTimestamp
	}
	return 0
}

// Grains defines the base
type Grains struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grains) Reset() {
	*x = Grains{}
	mi := &file_api_types_internal_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grains) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grains) ProtoMessage() {}

func (x *Grains) ProtoReflect() protoreflect.Message {
	mi := &file_api_types_internal_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grains.ProtoReflect.Descriptor instead.
func (*Grains) Descriptor() ([]byte, []int) {
	return file_api_types_internal_proto_rawDescGZIP(), []int{1}
}

var File_api_types_internal_proto protoreflect.FileDescriptor

var file_api_types_internal_proto_rawDesc = string([]byte{
	0x0a, 0x18, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x6e, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x22, 0x85, 0x03, 0x0a, 0x06, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02,
	0x69, 0x70, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2b,
	0x0a, 0x04, 0x74, 0x61, 0x67, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x74,
	0x79, 0x70, 0x65, 0x73, 0x2e, 0x4d, 0x69, 0x6e, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x61, 0x67, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x04, 0x74, 0x61, 0x67, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x61,
	0x72, 0x63, 0x68, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x72, 0x63, 0x68, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2d, 0x0a, 0x12, 0x72, 0x65, 0x67,
	0x69, 0x73, 0x74, 0x72, 0x79, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18,
	0x15, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x79, 0x54,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x6e, 0x6c, 0x69,
	0x6e, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x16, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0f, 0x6f, 0x6e, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x2b, 0x0a, 0x11, 0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x5f, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x17, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10,
	0x6f, 0x66, 0x66, 0x6c, 0x69, 0x6e, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x1a, 0x37, 0x0a, 0x09, 0x54, 0x61, 0x67, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x08, 0x0a, 0x06, 0x47, 0x72, 0x61,
	0x69, 0x6e, 0x73, 0x2a, 0x1d, 0x0a, 0x09, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x4b, 0x69, 0x6e, 0x64,
	0x12, 0x10, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x55, 0x6e, 0x6b, 0x6e, 0x6f, 0x77, 0x6e,
	0x10, 0x00, 0x42, 0x4e, 0x0a, 0x16, 0x69, 0x6f, 0x2e, 0x76, 0x69, 0x6e, 0x65, 0x2e, 0x6d, 0x61,
	0x63, 0x6f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x74, 0x79, 0x70, 0x65, 0x73, 0x42, 0x09, 0x4d, 0x61,
	0x63, 0x6f, 0x54, 0x79, 0x70, 0x65, 0x73, 0x50, 0x01, 0x5a, 0x27, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x76, 0x69, 0x6e, 0x65, 0x2d, 0x69, 0x6f, 0x2f, 0x6d, 0x61,
	0x63, 0x6f, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x3b, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_api_types_internal_proto_rawDescOnce sync.Once
	file_api_types_internal_proto_rawDescData []byte
)

func file_api_types_internal_proto_rawDescGZIP() []byte {
	file_api_types_internal_proto_rawDescOnce.Do(func() {
		file_api_types_internal_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_types_internal_proto_rawDesc), len(file_api_types_internal_proto_rawDesc)))
	})
	return file_api_types_internal_proto_rawDescData
}

var file_api_types_internal_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_types_internal_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_types_internal_proto_goTypes = []any{
	(EventKind)(0), // 0: types.EventKind
	(*Minion)(nil), // 1: types.Minion
	(*Grains)(nil), // 2: types.Grains
	nil,            // 3: types.Minion.TagsEntry
}
var file_api_types_internal_proto_depIdxs = []int32{
	3, // 0: types.Minion.tags:type_name -> types.Minion.TagsEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_types_internal_proto_init() }
func file_api_types_internal_proto_init() {
	if File_api_types_internal_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_types_internal_proto_rawDesc), len(file_api_types_internal_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_types_internal_proto_goTypes,
		DependencyIndexes: file_api_types_internal_proto_depIdxs,
		EnumInfos:         file_api_types_internal_proto_enumTypes,
		MessageInfos:      file_api_types_internal_proto_msgTypes,
	}.Build()
	File_api_types_internal_proto = out.File
	file_api_types_internal_proto_goTypes = nil
	file_api_types_internal_proto_depIdxs = nil
}
