//
//Copyright 2025 The maco Authors
//
//This program is offered under a commercial and under the AGPL license.
//For AGPL licensing, see below.
//
//AGPL licensing:
//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU Affero General Public License as published by
//the Free Software Foundation, either version 3 of the License, or
//(at your option) any later version.
//
//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU Affero General Public License for more details.
//
//You should have received a copy of the GNU Affero General Public License
//along with this program.  If not, see <https://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: api/errors/errors.proto

package errors

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Code int32

const (
	Code_Ok              Code = 0
	Code_Unknown         Code = 1
	Code_Internal        Code = 2
	Code_BadRequest      Code = 3
	Code_Unauthorized    Code = 4
	Code_Forbidden       Code = 5
	Code_NotFound        Code = 6
	Code_Conflict        Code = 7
	Code_TooManyRequests Code = 8
	Code_ClientClosed    Code = 9
	Code_NotImplemented  Code = 10
	Code_Unavailable     Code = 11
	Code_GatewayTimeout  Code = 12
)

// Enum value maps for Code.
var (
	Code_name = map[int32]string{
		0:  "Ok",
		1:  "Unknown",
		2:  "Internal",
		3:  "BadRequest",
		4:  "Unauthorized",
		5:  "Forbidden",
		6:  "NotFound",
		7:  "Conflict",
		8:  "TooManyRequests",
		9:  "ClientClosed",
		10: "NotImplemented",
		11: "Unavailable",
		12: "GatewayTimeout",
	}
	Code_value = map[string]int32{
		"Ok":              0,
		"Unknown":         1,
		"Internal":        2,
		"BadRequest":      3,
		"Unauthorized":    4,
		"Forbidden":       5,
		"NotFound":        6,
		"Conflict":        7,
		"TooManyRequests": 8,
		"ClientClosed":    9,
		"NotImplemented":  10,
		"Unavailable":     11,
		"GatewayTimeout":  12,
	}
)

func (x Code) Enum() *Code {
	p := new(Code)
	*p = x
	return p
}

func (x Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Code) Descriptor() protoreflect.EnumDescriptor {
	return file_api_errors_errors_proto_enumTypes[0].Descriptor()
}

func (Code) Type() protoreflect.EnumType {
	return &file_api_errors_errors_proto_enumTypes[0]
}

func (x Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Code.Descriptor instead.
func (Code) EnumDescriptor() ([]byte, []int) {
	return file_api_errors_errors_proto_rawDescGZIP(), []int{0}
}

type Error struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          Code                   `protobuf:"varint,1,opt,name=code,proto3,enum=errors.Code" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Causes        []*any1.Any            `protobuf:"bytes,4,rep,name=causes,proto3" json:"causes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Error) Reset() {
	*x = Error{}
	mi := &file_api_errors_errors_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_api_errors_errors_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_api_errors_errors_proto_rawDescGZIP(), []int{0}
}

func (x *Error) GetCode() Code {
	if x != nil {
		return x.Code
	}
	return Code_Ok
}

func (x *Error) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Error) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *Error) GetCauses() []*any1.Any {
	if x != nil {
		return x.Causes
	}
	return nil
}

var File_api_errors_errors_proto protoreflect.FileDescriptor

const file_api_errors_errors_proto_rawDesc = "" +
	"\n" +
	"\x17api/errors/errors.proto\x12\x06errors\x1a\x19google/protobuf/any.proto\"\x89\x01\n" +
	"\x05Error\x12 \n" +
	"\x04code\x18\x01 \x01(\x0e2\f.errors.CodeR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x16\n" +
	"\x06detail\x18\x03 \x01(\tR\x06detail\x12,\n" +
	"\x06causes\x18\x04 \x03(\v2\x14.google.protobuf.AnyR\x06causes*\xd6\x01\n" +
	"\x04Code\x12\x06\n" +
	"\x02Ok\x10\x00\x12\v\n" +
	"\aUnknown\x10\x01\x12\f\n" +
	"\bInternal\x10\x02\x12\x0e\n" +
	"\n" +
	"BadRequest\x10\x03\x12\x10\n" +
	"\fUnauthorized\x10\x04\x12\r\n" +
	"\tForbidden\x10\x05\x12\f\n" +
	"\bNotFound\x10\x06\x12\f\n" +
	"\bConflict\x10\a\x12\x13\n" +
	"\x0fTooManyRequests\x10\b\x12\x10\n" +
	"\fClientClosed\x10\t\x12\x12\n" +
	"\x0eNotImplemented\x10\n" +
	"\x12\x0f\n" +
	"\vUnavailable\x10\v\x12\x12\n" +
	"\x0eGatewayTimeout\x10\fBR\n" +
	"\x17io.vine.maco.api.errorsB\n" +
	"MacoErrorsP\x01Z)github.com/vine-io/maco/api/errors;errorsb\x06proto3"

var (
	file_api_errors_errors_proto_rawDescOnce sync.Once
	file_api_errors_errors_proto_rawDescData []byte
)

func file_api_errors_errors_proto_rawDescGZIP() []byte {
	file_api_errors_errors_proto_rawDescOnce.Do(func() {
		file_api_errors_errors_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_errors_errors_proto_rawDesc), len(file_api_errors_errors_proto_rawDesc)))
	})
	return file_api_errors_errors_proto_rawDescData
}

var file_api_errors_errors_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_errors_errors_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_api_errors_errors_proto_goTypes = []any{
	(Code)(0),        // 0: errors.Code
	(*Error)(nil),    // 1: errors.Error
	(*any1.Any)(nil), // 2: google.protobuf.Any
}
var file_api_errors_errors_proto_depIdxs = []int32{
	0, // 0: errors.Error.code:type_name -> errors.Code
	2, // 1: errors.Error.causes:type_name -> google.protobuf.Any
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_errors_errors_proto_init() }
func file_api_errors_errors_proto_init() {
	if File_api_errors_errors_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_errors_errors_proto_rawDesc), len(file_api_errors_errors_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_api_errors_errors_proto_goTypes,
		DependencyIndexes: file_api_errors_errors_proto_depIdxs,
		EnumInfos:         file_api_errors_errors_proto_enumTypes,
		MessageInfos:      file_api_errors_errors_proto_msgTypes,
	}.Build()
	File_api_errors_errors_proto = out.File
	file_api_errors_errors_proto_goTypes = nil
	file_api_errors_errors_proto_depIdxs = nil
}
